### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by velocityzen** [h2non/google-oauth2-token#2]
Tried to run your example:
phantomjs-node: You don't have 'phantomjs' installed

After manually installed pahntomjs:
phantom stdout: TypeError: 'null' is not an object (evaluating 'element.dispatchEvent')
phantom stdout:   phantomjs://webpage.evaluate():5
  phantomjs://webpage.evaluate():6
  phantomjs://webpage.evaluate():6
[Error: Cannot retrieve the token. Timeout exceeded]

Any thoughts? node 4.2.1

**Comment by h2non** [comment]
Seems like Google changed (again) the sign-in form, so the scrapping is not working.

Here you have the implementation, so you can change the CSS selectors to fill the form properly:
https://github.com/h2non/nightmare-google-oauth2/blob/master/index.js#L25-L31

**Comment by Alexis01** [comment]
tried to run your example,
But  when i send the request y get this error 
Cannot retrieve the token: [Error: Cannot retrieve the token. Timeout exceeded]

Could you help me?

Thanks

**Comment by rajeshshegokar111** [comment]
Hi, 
     I am also facing same issues. also changed css selectors but could not work for me. below code for gmail page selectors
.wait('#Email')
      .type('input[type=email]', params.email)
      .click('input[id=next]')
      .wait(5000)
      .wait('#Passwd')
      .type('input[type=password]', params.password)
      .click('input[type=submit]')
      .wait(3000)

Please suggest something.. Thanks in advance

**Comment by h2non** [comment]
Didn't try for a while to be honest. There's required to inspect the web and adapt the script accordingly to perform the scrapping. Feel free to go ahead and send a PR. I can try when I've some free time.

**Comment by rajeshshegokar111** [comment]
Hi, just fixed issue.. I want to raise pull request for the nightmare-google-oauth2/index.js file.
but it is saying permission denied. Could you please give me permission to raise pull request..

**Comment by h2non** [comment]
You should be able to create a PR. There's no explicit permissions for third-party PRs. You've to fork the repo first.

**Comment by rajeshshegokar111** [comment]
Hi,
     I have created branch for this after checkout of Master.
Do you want me to direct commit to master and raise pull request

## 

Rajesh

**Comment by h2non** [comment]
Please, follow this steps:
https://guides.github.com/activities/contributing-to-open-source/#contributing

**Comment by rajeshshegokar111** [comment]
Hi,
       Thanks for sharing. I have just created pull request. from id
_rajeshshegokar111._
Please review & merge so that nobody will face the same issue. Attached
snapshot also.

## 

Rajesh

On Tue, Feb 23, 2016 at 1:21 AM, Tomás Aparicio notifications@github.com
wrote:

> Please, follow this steps:
> 
> https://guides.github.com/activities/contributing-to-open-source/#contributing
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/h2non/google-oauth2-token/issues/2#issuecomment-187351142
> .

## 

_Thanks & regards_,
Rajesh Shegokar
_Software Engineer_, Indieon Technologies,
_Mob-9890009869_

**Comment by h2non** [comment]
Merged and fix shipped in 0.1.6. Feel free to update the package from `npm`.

Let's close this for now.

**Comment by rajeshshegokar111** [comment]
Thnx for merging.

One issue with
_google-oauth2-token https://github.com/h2non/google-oauth2-token npm
module is it is not working with amazon linux. i tried on ubuntu so it
worked. Need to make it compatible with all the os._

_-_
_Thanks,_
-  Rajesh*

On Tue, Feb 23, 2016 at 1:49 AM, Tomás Aparicio notifications@github.com
wrote:

> Closed #2 https://github.com/h2non/google-oauth2-token/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/h2non/google-oauth2-token/issues/2#event-560323772.

## 

_Thanks & regards_,
Rajesh Shegokar
_Software Engineer_, Indieon Technologies,
_Mob-9890009869_

**Comment by h2non** [comment]
Why is not working? I would need a bit more info here to help you. Which error do you have?

**Comment by rajeshshegokar111** [comment]
Hi,
    Actually i tried npm i google-oauth2-token on amazon linux EC2 machine
so i got following error. snaposhot attached. i think some issue with
binary modules.
   Let me know if any solution for this.

## 

Rajesh

On Tue, Feb 23, 2016 at 2:39 AM, Tomás Aparicio notifications@github.com
wrote:

> Why is not working? I would need a bit more info here to help you. Which
> error do you have?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/h2non/google-oauth2-token/issues/2#issuecomment-187384295
> .

## 

_Thanks & regards_,
Rajesh Shegokar
_Software Engineer_, Indieon Technologies,
_Mob-9890009869_

**Comment by h2non** [comment]
PhanthomJS is not properly installed I believe.

**Comment by rajeshshegokar111** [comment]
Ohh ok. I will try to install again lets see.

One more thing , is there any similar module for the facebook as i need
access token & user id from facebook. I have created appid & secret.
anything similar to google-oauth2-token?

-Thanks

Rajesh

On Tue, Feb 23, 2016 at 4:04 PM, Tomás Aparicio notifications@github.com
wrote:

> PhanthomJS is not properly installed I believe.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/h2non/google-oauth2-token/issues/2#issuecomment-187644694
> .

## 

_Thanks & regards_,
Rajesh Shegokar
_Software Engineer_, Indieon Technologies,
_Mob-9890009869_

**Comment by h2non** [comment]
No, there's nothing similar, but I do believe you can adapt `google-auth2-token` package for Facebook without too much troubles.
