### ISSUE TITLE
Cannot retrieve the token. Timeout exceeded

### ISSUE THREAD

**Issue by ishmangit** [h2non/google-oauth2-token#4]
When I try to get the token by Command-line interface

Any ideas?
Thanks!

**Comment by h2non** [comment]
Google changed the log in UI, therefore the [current implementation](https://github.com/h2non/nightmare-google-oauth2/blob/master/index.js#L20-L50) doesn't work. There's required to adapt the code, but I don't have time now. Feel free to open a PR.

**Comment by h2non** [comment]
This should be fixed with #2. Closing for now.
